version: '3.8'
services:
  flask_app:
    build: ./app
    container_name: flask_app
    volumes:
      - ./app:/app
    env_file:
      - ./env/.env
    ports:
      - "3000:5000"
    depends_on:
      - redis
      - dynamodb_local
    networks:
      - app_network

  dynamodb_local:
    image: amazon/dynamodb-local
    container_name: dynamodb_local
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb"
    networks:
      - app_network

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app_network

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - flask_app
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
